#!/bin/bash
#SBATCH --account=ARLAP02642530
#SBATCH --qos=debug  #quality of servicey
#SBATCH --nodes=1
#SBATCH --ntasks=128
#SBATCH --ntasks-per-node=128
#SBATCH --export=ALL
#SBATCH --time=00:30:00          # total run time limit (HH:MM:SS)

cd $SLURM_SUBMIT_DIR

#On carpenter: module load python/3.10.4

unset DISPLAY

#Install with:
#pip uninstall pyvista vtk vtk-osmesa -y
#pip install pyvista --no-deps
#pip install numpy pillow scooby pooch imageio matplotlib
#pip install --extra-index-url https://wheels.vtk.org vtk-osmesa

#Use this to activate environment
#python3.11 -m venv ~/pv_env

source ~/pv_env/bin/activate

#python3.11 P_RMS.py
#python3.11 shearTrack.py
#python3.11 makeSlices.py
python3.11 animateOrtho.py
#python3.11 animateFullBody.py
#python3.11 makePSD.py
#python3.11 PhaseAvg.py
#python3.11 dynModeDecomp.py 
